# Production
# baseURL = "https://cyber-unh.org"
# Development
baseURL = "https://jolly-poitras-197c4b.netlify.com/"
languageCode = "en-us"
title = "UNH Cyber Center"
theme = "Cyber"

sectionPagesMenu = "main"

[permalinks]
	news = "/news/:year/:month/:slug/"
	events = "/events/:year/:month/:slug/"
	resources = "/resources/:year/:slug/"

[params]
	Nickname = "UNH Cyber"
	Greeting = "Club Meets Mondays at 6 in Kingsbury CS Conference Room"
	Twitter = "https://twitter.com"
	Facebook = "https://facebook.com"
	Email = "user@example.com"
	baseURLIsRoot = true

	[[params.Topics]]
		name = "Dark Web"
		description = "TODO: add more details"
		image = "deep-web.jpg"
	[[params.Topics]]
		name = "Cryptocurrency"
		description = "TODO: add more details"
		image = "Bitcoin.svg"
	[[params.Topics]]
		name = "Hacking"
		description = "TODO: add more details"
		image = "hacking.jpg"
	
	[[params.Team]]
		Name = "Ken Graf"
		Role = "Head"
		Image = ""
		Twitter = ""
		Facebook = ""
		Email = ""
	
	[[params.Team]]
		Name = "Max DelRio"
		Role = "Captain"
		Image = ""
		Twitter = ""
		Facebook = ""
		Email = ""

	[[params.Team]]
		Name = "Ben Patton"
		Role = "Networking"
		Image = ""
		Twitter = ""
		Facebook = ""
		Email = ""
	


[menu]
	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"
		weight = 1
	[[menu.main]]
		identifier = "news"
		name = "News"
		url = "/news/"
		weight = 5
	[[menu.main]]
		identifier = "events"
		name = "Events"
		url = "/events/"
		weight = 3
	[[menu.main]]
		identifier = "resources"
		name = "Resources"
		url = "/resources/"
		weight = 4
	[[menu.main]]
		identifier = "contact"
		name = "Contact Us"
		url = "/contact/"
		weight = 2

[services]
	[services.instagram]
		disableInlineCSS = true
	[services.twitter]
    	disableInlineCSS = true

[privacy]
	[privacy.instagram]
		disable = false
		simple = true
	[privacy.twitter]
		disable = false
		enableDNT = true
		simple = true
	[privacy.vimeo]
		disable = false
		simple = false
	[privacy.youtube]
		disable = false
		privacyEnhanced = true